---
title: "Run BKMR Simulations"
output: pdf_document
date: "2023-10-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(miceadds)
source.all(path="R")
```

## Scenario 1

```{r}
# simulate data (default dimensions set in simulate_scenario functions)
data1 <- simulate_scenario1()

# fit the bkmr model
bkmr_m1 <- fit_BKMR(data1$y_obs, data1$X_obs)
bkmr_group_m1 <- fit_BKMR_group(data1$y_obs, data1$X_obs)
bkmr_coef1 <- get_coefficients_BKMR(bkmr_m1)
```


```{r}
# summarize results
bkmr_acc <- summarize_accuracy_BKMR(data1, bkmr_coef1)
bkmr_ESS <- summarize_mixing_BKMR(bkmr_coef1)
```


```{r}
# run full simulation for BKMR and BKMR_group
seed_list <- c(1234)
scenario <- 1
for (i in seed_list) {
  bkmr_sim_save <- run_sim_BKMR(scenario=scenario,
              save_output=TRUE,
              path=paste0("simulations/BKMR/scenario", scenario, "/"),
              datagen_seed=i)
  
  bkmr_group_sim_save <- run_sim_BKMR_group(scenario=scenario,
              save_output=TRUE,
              path=paste0("simulations/BKMR_group/scenario", scenario, "/"),
              datagen_seed=i)
}
```




