---
title: "Motivating simulations for introduction"
output: html_document
date: "2023-11-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mvtnorm)
library(rstan)
library(shinystan)
library(psych)
```

# Rank-1 simulations

```{r}
############ data generation #############

# set random seed
set.seed(1234)

# set parameter values
p <- 5
TT <- 3
n_obs <- 200
phi <- 0.7
sigma2 <- 5

# specify covariance matrix for eta_i's over time
Phi_mat <- matrix(data = rep(1, TT*TT), nrow=TT)
for (i in 1:TT) {
  for (j in 1:TT) {
    if (j != i) {
      Phi_mat[i,j] <- phi
    }
  }
}

# generate x_i's
X_obs <- matrix(data=rep(NA, n_obs * p * TT), nrow=n_obs)
for (i in 1:n_obs) {
  for (j in 1:p) {
    X_obs[i, (1 + (j-1) * TT):(j * TT)] <- rmvnorm(n=1, sigma = Phi_mat)
  }
}

# specify beta and omega (main effects)
beta1 <- c(1, 3, 2, -1,-2)
omega1 <- c(0.25, 0.25, 0.5)

# specify vector of main-effect coefficients based on the above to generate y's
theta <- as.vector(omega1 %*% t(beta1))

# display true theta
theta

# generate y_i's
y_obs <- rep(NA, n_obs)
for (i in 1:n_obs) {
  y_obs[i] <- rnorm(n=1, mean = X_obs[i,] %*% theta, sd = sqrt(sigma2))
}
```


```{r}
# try regressing y on x
m1 <- lm(y_obs ~ X_obs)
summary(m1)
```


```{r}
# fit bayesian linear regression in stan
m_simple <- stan_model("Stan/intro_figure_simple_linreg.stan")
```

```{r}
options(mc.cores = parallel::detectCores())
fit_simple <- sampling(m_simple, list(N=n_obs,
                                      p=p,
                                      TT=TT,
                                      X=X_obs,
                                      y=y_obs),
                       chains=4,
                       iter=2000,
                       seed=1234)
```

```{r}
# extract samples
post_samples_simple <- extract(fit_simple)
```

```{r}
# make plot of posterior intervals of betas
beta_upper <- rep(NA, p*TT)
beta_lower <- rep(NA, p*TT)
beta_mean <- rep(NA, p*TT)
beta_true <- theta

for (i in 1:(p*TT)) {
  beta_upper[i] <- quantile(post_samples_simple$beta[,i], probs=c(0.975))
  beta_lower[i] <- quantile(post_samples_simple$beta[,i], probs=c(0.025))
  beta_mean[i] <- mean(post_samples_simple$beta[,i])
}

labels <- c("Exp1,T1", "Exp1,T2", "Exp1,T3",
           "Exp2,T1", "Exp2,T2", "Exp2,T3",
           "Exp3,T1", "Exp3,T2", "Exp3,T3",
           "Exp4,T1", "Exp4,T2", "Exp4,T3",
           "Exp5,T1", "Exp5,T2", "Exp5,T3")

# define df for plotting
beta_interval_df <- data.frame(labels, beta_lower, beta_upper, beta_true)
beta_interval_df$labels <- factor(beta_interval_df$labels,
                                  levels = rev(beta_interval_df$labels))

# make plot
beta_plot_simple <- ggplot(data=beta_interval_df, aes(x=labels, y=beta_true)) +
  geom_errorbar(aes(ymin=beta_lower, ymax=beta_upper)) +
  geom_hline(yintercept=0, color="black") +
  geom_point(color="red") +
  coord_flip() +
  labs(title="Simple linear regression",
       y="", x="") +
  ylim(-2,2.5)

beta_plot_simple

# print mean squared difference between the posterior means of betas and the true value
mean((beta_true - beta_mean) * (beta_true - beta_mean))
```

## Now, refit assuming the coefficients are rank-1:

```{r}
# fit bayesian linear regression in stan
m_rank1 <- stan_model("Stan/intro_figure_rank1.stan")
```

```{r}
options(mc.cores = parallel::detectCores())
fit_rank1 <- sampling(m_rank1, list(N=n_obs,
                                      p=p,
                                      TT=TT,
                                      X=X_obs,
                                      y=y_obs),
                       chains=4,
                       iter=2000,
                       seed=1234)
```

```{r}
# extract samples
post_samples_rank1 <- extract(fit_rank1)
```

```{r}
# make plot of posterior intervals of betas
beta_upper <- rep(NA, p*TT)
beta_lower <- rep(NA, p*TT)
beta_mean <- rep(NA, p*TT)
beta_true <- theta

for (i in 1:(p*TT)) {
  beta_upper[i] <- quantile(post_samples_rank1$theta[,i], probs=c(0.975))
  beta_lower[i] <- quantile(post_samples_rank1$theta[,i], probs=c(0.025))
  beta_mean[i] <- mean(post_samples_rank1$theta[,i])
}

labels <- c("Exp1,T1", "Exp1,T2", "Exp1,T3",
           "Exp2,T1", "Exp2,T2", "Exp2,T3",
           "Exp3,T1", "Exp3,T2", "Exp3,T3",
           "Exp4,T1", "Exp4,T2", "Exp4,T3",
           "Exp5,T1", "Exp5,T2", "Exp5,T3")

# define df for plotting
beta_interval_df <- data.frame(labels, beta_lower, beta_upper, beta_true)
beta_interval_df$labels <- factor(beta_interval_df$labels,
                                  levels = rev(beta_interval_df$labels))

# make plot
beta_plot_rank1 <- ggplot(data=beta_interval_df, aes(x=labels, y=beta_true)) +
  geom_errorbar(aes(ymin=beta_lower, ymax=beta_upper)) +
  geom_hline(yintercept=0, color="black") +
  geom_point(color="red") +
  coord_flip() +
  labs(title="Assuming rank-1 coefficients",
       y="", x="") +
  ylim(-2,2.5)

beta_plot_rank1

# print mean squared difference between the posterior means of betas and the true value
mean((beta_true - beta_mean) * (beta_true - beta_mean))
```

```{r}
# plot the graphs next to each other
library(cowplot)

# make plot
plot_grid(beta_plot_simple, beta_plot_rank1)
```





# Rank-2 simulations

```{r}
############ data generation #############

# set random seed
set.seed(1234)

# set parameter values
p <- 5
TT <- 3
n_obs <- 200
phi <- 0.7
sigma2 <- 5

# specify covariance matrix for eta_i's over time
Phi_mat <- matrix(data = rep(1, TT*TT), nrow=TT)
for (i in 1:TT) {
  for (j in 1:TT) {
    if (j != i) {
      Phi_mat[i,j] <- phi
    }
  }
}

# generate x_i's
X_obs <- matrix(data=rep(NA, n_obs * p * TT), nrow=n_obs)
for (i in 1:n_obs) {
  for (j in 1:p) {
    X_obs[i, (1 + (j-1) * TT):(j * TT)] <- rmvnorm(n=1, sigma = Phi_mat)
  }
}

# specify beta and omega (main effects)
beta1 <- c(1, 3, 2, 0, 0)
omega1 <- c(0.25, 0.25, 0.5)
beta2 <- c(0,0,0,-1,-2)
omega2 <- c(0.8,0.1,0.1)

# specify vector of main-effect coefficients based on the above to generate y's
theta <- as.vector(omega1 %*% t(beta1) + omega2 %*% t(beta2))

# display true theta
theta

# generate y_i's
y_obs <- rep(NA, n_obs)
for (i in 1:n_obs) {
  y_obs[i] <- rnorm(n=1, mean = X_obs[i,] %*% theta, sd = sqrt(sigma2))
}
```


```{r}
# try regressing y on x
m1 <- lm(y_obs ~ X_obs)
summary(m1)
```


```{r}
# fit bayesian linear regression in stan
m_simple <- stan_model("Stan/intro_figure_simple_linreg.stan")
```

```{r}
options(mc.cores = parallel::detectCores())
fit_simple <- sampling(m_simple, list(N=n_obs,
                                      p=p,
                                      TT=TT,
                                      X=X_obs,
                                      y=y_obs),
                       chains=4,
                       iter=2000,
                       seed=1234)
```

```{r}
# extract samples
post_samples_simple <- extract(fit_simple)
```

```{r}
# make plot of posterior intervals of betas
beta_upper <- rep(NA, p*TT)
beta_lower <- rep(NA, p*TT)
beta_mean <- rep(NA, p*TT)
beta_true <- theta

for (i in 1:(p*TT)) {
  beta_upper[i] <- quantile(post_samples_simple$beta[,i], probs=c(0.975))
  beta_lower[i] <- quantile(post_samples_simple$beta[,i], probs=c(0.025))
  beta_mean[i] <- mean(post_samples_simple$beta[,i])
}

labels <- c("Exp1,T1", "Exp1,T2", "Exp1,T3",
           "Exp2,T1", "Exp2,T2", "Exp2,T3",
           "Exp3,T1", "Exp3,T2", "Exp3,T3",
           "Exp4,T1", "Exp4,T2", "Exp4,T3",
           "Exp5,T1", "Exp5,T2", "Exp5,T3")

# define df for plotting
beta_interval_df <- data.frame(labels, beta_lower, beta_upper, beta_true)
beta_interval_df$labels <- factor(beta_interval_df$labels,
                                  levels = rev(beta_interval_df$labels))

# make plot
beta_plot_simple <- ggplot(data=beta_interval_df, aes(x=labels, y=beta_true)) +
  geom_errorbar(aes(ymin=beta_lower, ymax=beta_upper)) +
  geom_hline(yintercept=0, color="black") +
  geom_point(color="red") +
  coord_flip() +
  labs(title="Simple linear regression",
       y="", x="") +
  ylim(-2.5,2.5)

beta_plot_simple

# print mean squared difference between the posterior means of betas and the true value
mean((beta_true - beta_mean) * (beta_true - beta_mean))
```

## Now, refit assuming the coefficients are rank-1:

```{r}
# fit bayesian linear regression in stan
m_rank1 <- stan_model("Stan/intro_figure_rank1.stan")
```

```{r}
options(mc.cores = parallel::detectCores())
fit_rank1 <- sampling(m_rank1, list(N=n_obs,
                                      p=p,
                                      TT=TT,
                                      X=X_obs,
                                      y=y_obs),
                       chains=4,
                       iter=2000,
                       seed=1234)
```

```{r}
# extract samples
post_samples_rank1 <- extract(fit_rank1)
```

```{r}
# make plot of posterior intervals of betas
beta_upper <- rep(NA, p*TT)
beta_lower <- rep(NA, p*TT)
beta_mean <- rep(NA, p*TT)
beta_true <- theta

for (i in 1:(p*TT)) {
  beta_upper[i] <- quantile(post_samples_rank1$theta[,i], probs=c(0.975))
  beta_lower[i] <- quantile(post_samples_rank1$theta[,i], probs=c(0.025))
  beta_mean[i] <- mean(post_samples_rank1$theta[,i])
}

labels <- c("Exp1,T1", "Exp1,T2", "Exp1,T3",
           "Exp2,T1", "Exp2,T2", "Exp2,T3",
           "Exp3,T1", "Exp3,T2", "Exp3,T3",
           "Exp4,T1", "Exp4,T2", "Exp4,T3",
           "Exp5,T1", "Exp5,T2", "Exp5,T3")

# define df for plotting
beta_interval_df <- data.frame(labels, beta_lower, beta_upper, beta_true)
beta_interval_df$labels <- factor(beta_interval_df$labels,
                                  levels = rev(beta_interval_df$labels))

# make plot
beta_plot_rank1 <- ggplot(data=beta_interval_df, aes(x=labels, y=beta_true)) +
  geom_errorbar(aes(ymin=beta_lower, ymax=beta_upper)) +
  geom_hline(yintercept=0, color="black") +
  geom_point(color="red") +
  coord_flip() +
  labs(title="Assuming rank-1 coefficients",
       y="", x="") +
  ylim(-2.5,2.5)

beta_plot_rank1

# print mean squared difference between the posterior means of betas and the true value
mean((beta_true - beta_mean) * (beta_true - beta_mean))
```



```{r}
# plot the graphs next to each other
library(cowplot)

# make plot
plot_grid(beta_plot_simple, beta_plot_rank1)
```


## And now assume the coefficients are rank-2.

```{r}
# fit bayesian linear regression in stan
m_rank2 <- stan_model("Stan/intro_figure_rank2.stan")
```

```{r}
options(mc.cores = parallel::detectCores())
fit_rank2 <- sampling(m_rank2, list(N=n_obs,
                                      p=p,
                                      TT=TT,
                                      X=X_obs,
                                      y=y_obs),
                       chains=4,
                       iter=2000,
                       seed=1234)
```

```{r}
# extract samples
post_samples_rank2 <- extract(fit_rank2)
```

```{r}
# make plot of posterior intervals of betas
beta_upper <- rep(NA, p*TT)
beta_lower <- rep(NA, p*TT)
beta_mean <- rep(NA, p*TT)
beta_true <- theta

for (i in 1:(p*TT)) {
  beta_upper[i] <- quantile(post_samples_rank2$theta[,i], probs=c(0.975))
  beta_lower[i] <- quantile(post_samples_rank2$theta[,i], probs=c(0.025))
  beta_mean[i] <- mean(post_samples_rank2$theta[,i])
}

labels <- c("Exp1,T1", "Exp1,T2", "Exp1,T3",
           "Exp2,T1", "Exp2,T2", "Exp2,T3",
           "Exp3,T1", "Exp3,T2", "Exp3,T3",
           "Exp4,T1", "Exp4,T2", "Exp4,T3",
           "Exp5,T1", "Exp5,T2", "Exp5,T3")

# define df for plotting
beta_interval_df <- data.frame(labels, beta_lower, beta_upper, beta_true)
beta_interval_df$labels <- factor(beta_interval_df$labels,
                                  levels = rev(beta_interval_df$labels))

# make plot
beta_plot_rank2 <- ggplot(data=beta_interval_df, aes(x=labels, y=beta_true)) +
  geom_errorbar(aes(ymin=beta_lower, ymax=beta_upper)) +
  geom_hline(yintercept=0, color="black") +
  geom_point(color="red") +
  coord_flip() +
  labs(title="Assuming rank-2 coefficients",
       y="", x="") +
  ylim(-2.5,2.5)

beta_plot_rank2

# print mean squared difference between the posterior means of betas and the true value
mean((beta_true - beta_mean) * (beta_true - beta_mean))
```

```{r}
# plot the graphs next to each other
plot_grid(beta_plot_simple, beta_plot_rank2)
```





